use_text_file: true
text_file_path: "knowledge_base.txt"
use_chunking: true
subject: "customer support interactions"
model: "gpt-3.5-turbo"
num_interactions: 10
delay: 1
output_file: "synthetic_dataset.csv"
role1: "Customer"
role2: "Agent"
language: "hebrew"
topics:
 - "product returns"
 - "billing issues"
 - "technical support"
 - "account management"
 - "shipping inquiries"
